CREATE DATABASE IF NOT EXISTS reso;

USE reso;

CREATE TABLE IF NOT EXISTS payments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    payment_amount DECIMAL(10, 2) NOT NULL,
    gst_included TINYINT(1) NOT NULL,
    total_payable_amount DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

